/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goldenfarm;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sjoth
 */
public class AgricultureSpecialistForm extends javax.swing.JFrame {

    /**
     * Creates new form AgricultureSpecialistForm
     */
    public AgricultureSpecialistForm() {
        initComponents();
        updatetable();
    }
      private void updatetable()
  {
    DbConnect db = new DbConnect();
       db.connect();
       Boolean x;
       x=true;
       String query;
       query = "select farmerId,farmerName,regionCode from farmer ORDER BY regionCode ASC";
            
       
       Statement st = db.createStatement();
      try 
       {           
            ResultSet res =  st.executeQuery(query);
            Table_AgricSpec.setModel(DbUtils.resultSetToTableModel(res));
       } 
       catch (SQLException ex) 
       {
            Logger.getLogger(Production.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
       }
  
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMainMenu = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtEmployeeNumber = new javax.swing.JTextField();
        txtRegionCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtCellphoneNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_AgricSpec = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FARM COORDINATOR");

        jLabel2.setText("EMPLOYMENT NUMBER");

        jLabel3.setText("NAME");

        jLabel4.setText("SURNAME");

        jLabel5.setText("REGION CODE");

        jLabel6.setText("CELLPHONE NUMBER");

        jLabel7.setText("EMAIL ADDRESS");

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        btnMainMenu.setText("MAIN MENU");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnMainMenu)
                .addGap(42, 42, 42)
                .addComponent(btnAdd)
                .addGap(58, 58, 58)
                .addComponent(btnView)
                .addGap(68, 68, 68)
                .addComponent(btnUpdate)
                .addGap(97, 97, 97)
                .addComponent(btnDelete)
                .addGap(111, 111, 111)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnView)
                    .addComponent(btnAdd)
                    .addComponent(btnMainMenu))
                .addGap(33, 33, 33))
        );

        Table_AgricSpec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_AgricSpec);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("DEPLOYED COORDINATORS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtSurname)
                                    .addComponent(txtCellphoneNumber)
                                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRegionCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegionCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCellphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        new MainMenuForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AgricultureSpecialist a = new AgricultureSpecialist ();
         if (!(this.txtEmployeeNumber.getText().isEmpty()))
        {
            if (!(this.txtName.getText().isEmpty()))
            {
                if (!(this.txtSurname.getText().isEmpty()))
                {
                    a.setEmployeeNumber(this.txtEmployeeNumber.getText());
                     a.setRegionCode(this.txtRegionCode.getText());
                    a.setAgricName(this.txtName.getText());
                    a.setAgricSurname(this.txtSurname.getText());
                    a.setContactNumber(this.txtCellphoneNumber.getText());
                    a.setContactNumber(this.txtCellphoneNumber.getText());
                    a.setEmailAddress(this.txtEmailAddress.getText());
                    
                    a.AddAgricultureSpecialistDetails();  
                    if (a.getIsAdded())
                    {
                        
                     txtEmployeeNumber.setText("");
                     txtRegionCode.setText("");
                     txtName.setText("");
                     txtSurname.setText("");
                     txtCellphoneNumber.setText("");
                     txtEmailAddress.setText("");
                     
                     updatetable();
                     
                    }
                }
                 else
                {
                    JOptionPane.showMessageDialog(rootPane, "fill all the information required before you register this agricSpec");  
                }
            
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Make sure agricSpec name is not empty");  
            }          
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Make sure agricSpec ID is not empty");
        }                                          

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
                txtEmployeeNumber.setText("");
                txtRegionCode.setText("");
                txtName.setText("");
                txtSurname.setText("");
                txtCellphoneNumber.setText("");
                txtEmailAddress.setText("");
               
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        AgricultureSpecialist a = new AgricultureSpecialist ();
          if (!(this.txtEmployeeNumber.getText().isEmpty()))
        {
            if(!(this.txtName.getText().isEmpty()))
            {
                   a.setEmployeeNumber(this.txtEmployeeNumber.getText());
                   a.deleteAgricultureSpecialist();
                  
                   txtEmployeeNumber.setText("");
                   txtRegionCode.setText("");
                   txtName.setText("");
                   txtSurname.setText("");
                   txtCellphoneNumber.setText("");
                   txtEmailAddress.setText("");
                   
                    updatetable();
                    
                   
                   if (a.getIsDeleted())
                   {              
                        txtEmployeeNumber.setText("");
                        txtRegionCode.setText("");
                        txtName.setText("");
                         txtSurname.setText("");
                         txtCellphoneNumber.setText("");
                        txtEmailAddress.setText("");
                        updatetable();
                        
                        
                   }
                    }
            else
            {
               JOptionPane.showMessageDialog(rootPane, " CHECK agricSpec you want to delete "); 
            }
        }
        else
        {
           JOptionPane.showMessageDialog(rootPane, " CHECK agricSpec you want to delete ");
        }      
                                             

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        AgricultureSpecialist a = new AgricultureSpecialist ();
        if (!(this.txtEmployeeNumber.getText().isEmpty()))
        { 
            if (!(this.txtName.getText().isEmpty()))
            {  
                a.setEmployeeNumber(this.txtEmployeeNumber.getText());
                a.setRegionCode(this.txtRegionCode.getText());
                a.setAgricName(this.txtName.getText());
                a.setAgricSurname(this.txtSurname.getText());
                a.setContactNumber(this.txtCellphoneNumber.getText());  
                a.setEmailAddress(this.txtEmailAddress.getText());
                
                 
                 
                a.UpdateAgricultureSpecialist(this.txtEmployeeNumber.getText());
                txtEmployeeNumber.setText("");
                txtRegionCode.setText("");
                txtName.setText("");
                txtSurname.setText("");
                txtCellphoneNumber.setText("");
                txtEmailAddress.setText("");
                
                updatetable();
                
            }
         else
            {
                JOptionPane.showMessageDialog(rootPane, " CHECK  agricSpec before you update "); 
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, " CHECK  agricSpec before you update "); 
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        txtRegionCode.setText("");
         txtSurname.setText("");
        txtName.setText("");
       txtCellphoneNumber.setText("");
        txtEmailAddress.setText("");
        
        
        AgricultureSpecialist a = new AgricultureSpecialist();
        a.setEmployeeNumber(this.txtEmployeeNumber.getText());
       
        if (!(this.txtEmployeeNumber.getText().isEmpty()))
        {      
              try
              {
                   ResultSet rec = a.ViewAgricultureSpecialist(a.getEmployeeNumber());
                   while (rec.next())
                   {    
                       this.txtRegionCode.setText(rec.getString(2));
                       this.txtName.setText(rec.getString(3));
                       this.txtSurname.setText(rec.getString(4));
                       this.txtCellphoneNumber.setText(rec.getString(5));
                       this.txtEmailAddress.setText(rec.getString(6));        
                   }
                   
                   if (!(this.txtName.getText().isEmpty()))
                         {
                        
                           JOptionPane.showMessageDialog(rootPane, " the agricSpec exit in the database");  
                         }
                   else
                         {
                             JOptionPane.showMessageDialog(rootPane, " this agricSpec does  not exist in the system. register him or her first");
                            
                         }
               }   
               catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(rootPane, ex.getMessage()); 
                   
               }
        }
        else
        {
               JOptionPane.showMessageDialog(rootPane, "Make sure employment number is not empty");
        }                                        

    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgricultureSpecialistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgricultureSpecialistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgricultureSpecialistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgricultureSpecialistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgricultureSpecialistForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_AgricSpec;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCellphoneNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEmployeeNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRegionCode;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
