/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goldenfarm;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sjoth
 */
public class FarmerForm extends javax.swing.JFrame {

    /**
     * Creates new form FarmerForm
     */
    public FarmerForm() {
        initComponents();
        updatetable();
        updatetable2();
         
    }
    private void updatetable()
  {
    DbConnect db = new DbConnect();
       db.connect();
       Boolean x;
       x=true;
       String query;
       query = "select emplyNum,Name,regionCode from aagricSpec ORDER BY regionCode ASC";
            
       
       Statement st = db.createStatement();
      try 
       {           
            ResultSet res =  st.executeQuery(query);
            Table_Farmer.setModel(DbUtils.resultSetToTableModel(res));
       } 
       catch (SQLException ex) 
       {
            Logger.getLogger(Production.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
       }
  
  }
 private void updatetable2()
  {
    DbConnect db = new DbConnect();
       db.connect();
       Boolean x;
       x=true;
       String query;
       query = "select regionCode,regionName from region ORDER BY regionCode ASC";
            
       
       Statement st = db.createStatement();
      try 
       {           
            ResultSet res =  st.executeQuery(query);
            Table_FarmingTypes.setModel(DbUtils.resultSetToTableModel(res));
       } 
       catch (SQLException ex) 
       {
            Logger.getLogger(Production.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
       }
  
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMainMenu = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtFarmerId = new javax.swing.JTextField();
        txtFarmerName = new javax.swing.JTextField();
        txtFarmerSurname = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtCellphone = new javax.swing.JTextField();
        txtNextOfKeen = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txtRegionCode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Farmer = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_FarmingTypes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FARMER REGISTRATION");

        jLabel2.setText("FARMER ID");

        jLabel3.setText("FARMER NAME");

        jLabel4.setText("FARMER SURNAME");

        jLabel6.setText("DATE OF BIRTH");

        jLabel7.setText("CELLPHONE NUMBER");

        jLabel8.setText("NEXT OF KEEN");

        jLabel9.setText("REGION CODE");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        btnMainMenu.setText("MAIN MENU");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMainMenu)
                .addGap(110, 110, 110)
                .addComponent(btnAdd)
                .addGap(125, 125, 125)
                .addComponent(btnView)
                .addGap(93, 93, 93)
                .addComponent(btnUpdate)
                .addGap(98, 98, 98)
                .addComponent(btnDelete)
                .addGap(52, 52, 52)
                .addComponent(btnClear)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu)
                    .addComponent(btnAdd)
                    .addComponent(btnView)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addGap(28, 28, 28))
        );

        txtNextOfKeen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextOfKeenActionPerformed(evt);
            }
        });

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));

        Table_Farmer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_Farmer);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("REGISTERED FARMERS");

        Table_FarmingTypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Table_FarmingTypes);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("AVAILABLE TYPES OF FARMING");

        jLabel12.setText("GENDER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNextOfKeen, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRegionCode, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(124, 124, 124)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFarmerSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFarmerName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFarmerId, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))))))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFarmerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFarmerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFarmerSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNextOfKeen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRegionCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNextOfKeenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextOfKeenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextOfKeenActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
         new MainMenuForm().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         Farmer f = new Farmer ();
         if (!(this.txtFarmerId.getText().isEmpty()))
        {
            if (!(this.txtFarmerName.getText().isEmpty()))
            {
                if (!(this.txtFarmerSurname.getText().isEmpty()))
                {
                    f.setFarmerID(this.txtFarmerId.getText());
                    f.setName(this.txtFarmerName.getText());
                    f.setSurname(this.txtFarmerSurname.getText());
                    f.setDateOfBirth(this.txtDateOfBirth.getText());
                    f.setGender(this.cmbGender.getSelectedItem().toString());
                    f.setNextOfKeen(this.txtNextOfKeen.getText());
                    f.setContactNumber(this.txtCellphone.getText());
                    f.setRegionCode(this.txtRegionCode.getText());
                    
                    f.AddFarmerDetails();  
                    if (f.getFarmerAdded())
                    {
                        
                     txtFarmerId.setText("");
                     txtFarmerName.setText("");
                     txtFarmerSurname.setText("");
                     txtDateOfBirth.setText("");
                     txtNextOfKeen.setText("");
                     txtCellphone.setText("");
                     txtRegionCode.setText("");
                     updatetable();
                     updatetable2();
                    }
                }
                 else
                {
                    JOptionPane.showMessageDialog(rootPane, "fill all the information required before you register this student");  
                }
            
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Make sure student name is not empty");  
            }          
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Make sure student ID is not empty");
        }      
               
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
                txtFarmerId.setText("");
                txtFarmerName.setText("");
                txtFarmerSurname.setText("");
               txtDateOfBirth.setText("");
                txtNextOfKeen.setText("");
                txtCellphone.setText("");
               txtRegionCode.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        Farmer f = new Farmer ();
          if (!(this.txtFarmerId.getText().isEmpty()))
        {
            if(!(this.txtFarmerName.getText().isEmpty()))
            {
                   f.setFarmerID(this.txtFarmerId.getText());
                   f.deleteFarmer();
                  
                   txtFarmerId.setText("");
                   txtFarmerName.setText("");
                   txtFarmerSurname.setText("");
                 txtDateOfBirth.setText("");
                   txtNextOfKeen.setText("");
                   txtCellphone.setText("");
                   txtRegionCode.setText("");
                    updatetable();
                    updatetable2();
                   
                   if (f.getFarmerDeleted())
                   {              
                       txtFarmerId.setText("");
                       txtFarmerName.setText("");
                       txtFarmerSurname.setText("");
                     
                       txtNextOfKeen.setText("");
                       txtCellphone.setText("");
                       txtRegionCode.setText("");
                        updatetable();
                        updatetable2();
                        
                   }
                    }
            else
            {
               JOptionPane.showMessageDialog(rootPane, " CHECK farmer you want to delete "); 
            }
        }
        else
        {
           JOptionPane.showMessageDialog(rootPane, " CHECK farmer you want to delete ");
        }      
                                             

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         txtFarmerSurname.setText("");
        txtFarmerName.setText("");
       txtDateOfBirth.setText("");
        txtNextOfKeen.setText("");
        txtCellphone.setText("");
        txtRegionCode.setText("");
        
        Farmer s = new Farmer();
        s.setFarmerID(this.txtFarmerId.getText());
       
        if (!(this.txtFarmerId.getText().isEmpty()))
        {      
              try
              {
                   ResultSet rec = s.ViewFarmer(s.getFarmerID());
                   while (rec.next())
                   {              
                       this.txtFarmerName.setText(rec.getString(2));
                       this.txtFarmerSurname.setText(rec.getString(3));
                       this.txtNextOfKeen.setText(rec.getString(6));
                       this.txtCellphone.setText(rec.getString(7));
                       this.cmbGender.setSelectedItem(rec.getString(5));
                       this.txtDateOfBirth.setText(rec.getString(4));
                       this.txtRegionCode.setText(rec.getString(8));
                            
                   }
                   
                   if (!(this.txtFarmerName.getText().isEmpty()))
                         {
                        
                           JOptionPane.showMessageDialog(rootPane, " the farmer exit in the database");  
                         }
                   else
                         {
                             JOptionPane.showMessageDialog(rootPane, " this farmer does  not exist in the system. register him or her first");
                            
                         }
               }   
               catch(Exception ex)
               {
                   JOptionPane.showMessageDialog(rootPane, ex.getMessage()); 
                   
               }
        }
        else
        {
               JOptionPane.showMessageDialog(rootPane, "Make sure farmer ID is not empty");
        }                                        

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         Farmer s = new Farmer ();
        if (!(this.txtFarmerId.getText().isEmpty()))
        { 
            if (!(this.txtFarmerName.getText().isEmpty()))
            {  
                s.setFarmerID(this.txtFarmerId.getText());
                s.setName(this.txtFarmerName.getText());
                s.setSurname(this.txtFarmerSurname.getText());
                s.setDateOfBirth(this.txtDateOfBirth.getText());  
                s.setNextOfKeen(this.txtNextOfKeen.getText());
                s.setContactNumber(this.txtCellphone.getText());
                  s.setRegionCode(this.txtRegionCode.getText());
                 
                s.UpdateFarmer(this.txtFarmerId.getText());
                txtFarmerId.setText("");
                txtFarmerName.setText("");
                txtFarmerSurname.setText("");
                txtDateOfBirth.setText("");
                txtNextOfKeen.setText("");
                txtCellphone.setText("");
                txtRegionCode.setText("");
                updatetable();
                
        updatetable2();
            }
         else
            {
                JOptionPane.showMessageDialog(rootPane, " CHECK  farmer before you update "); 
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, " CHECK  farmer before you update "); 
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Farmer;
    private javax.swing.JTable Table_FarmingTypes;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCellphone;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtFarmerId;
    private javax.swing.JTextField txtFarmerName;
    private javax.swing.JTextField txtFarmerSurname;
    private javax.swing.JTextField txtNextOfKeen;
    private javax.swing.JTextField txtRegionCode;
    // End of variables declaration//GEN-END:variables
}
